### ISSUE TITLE
gates inaccessible and eyes staying open 

### ISSUE THREAD

**Issue by superon** [OpenlyFay/AncientGateways#1]
encountered these 2 issues, i say issues but maybe they're intended..  will detail them here anyway and just in case 👍 
if i tag a gate with specific set of glyphs, then later decide i put the gate in the wrong place so put it somewhere else (using the same glyph set) that gate will be able to open to another gate but won't be able to be opened by another gate.

also opening a gate with this replaced gate appears to open the eye (on the linked gate) but create no visible portal, now the eye is open because the portal doesn't close (or something).   when this gate (with the open eye) is now opened from another gate the portal appears with a closed eye which resets to closed when closed :)

**Comment by VisualEhrmanntraut** [comment]
Encountering this issue on my server as well. It would be nice if this gets fixed or at least the author responds :/

**Comment by OpenlyFay** [comment]
Fixed on github and dev builds, will be fixed on public next release

**Comment by superon** [comment]
<3
