### ISSUE TITLE
suggestion redstone output on active eye

### ISSUE THREAD

**Issue by superon** [OpenlyFay/AncientGateways#3]
just that really, i think it'd be neat to be able to simply plug redstone stuff on it rather than going round the houses with observers and all that.
also and maybe alternatively how about having redstone input on the top so they can be activated with a signal..  this would make it easier for those with arms too short to reach the core :)

**Comment by OpenlyFay** [comment]
Implemented comparator output now that there are several types of connections implemented, additionally there's a config option to make a cheap throwable/dispensable item activate a gateway on impact
